itsm/config/routes.rb
Rails.application.routes.draw do
  resources :service_provisions
  resources :services
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

itsm/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

itsm/app/models/category.rb
class Category < ApplicationRecord
    has_many :categories
end

itsm/app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
end

itsm/app/models/service_provision.rb
class ServiceProvision < ApplicationRecord
  belongs_to :service_provision
end

itsm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

itsm/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :subsidized_amount)
    end
end

itsm/app/controllers/service_provisions_controller.rb
class ServiceProvisionsController < ApplicationController
  before_action :set_service_provision, only: %i[ show edit update destroy ]

  # GET /service_provisions or /service_provisions.json
  def index
    @service_provisions = ServiceProvision.all
  end

  # GET /service_provisions/1 or /service_provisions/1.json
  def show
  end

  # GET /service_provisions/new
  def new
    @service_provision = ServiceProvision.new
  end

  # GET /service_provisions/1/edit
  def edit
  end

  # POST /service_provisions or /service_provisions.json
  def create
    @service_provision = ServiceProvision.new(service_provision_params)

    respond_to do |format|
      if @service_provision.save
        format.html { redirect_to service_provision_url(@service_provision), notice: "Service provision was successfully created." }
        format.json { render :show, status: :created, location: @service_provision }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_provision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_provisions/1 or /service_provisions/1.json
  def update
    respond_to do |format|
      if @service_provision.update(service_provision_params)
        format.html { redirect_to service_provision_url(@service_provision), notice: "Service provision was successfully updated." }
        format.json { render :show, status: :ok, location: @service_provision }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_provision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_provisions/1 or /service_provisions/1.json
  def destroy
    @service_provision.destroy

    respond_to do |format|
      format.html { redirect_to service_provisions_url, notice: "Service provision was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provision
      @service_provision = ServiceProvision.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_provision_params
      params.require(:service_provision).permit(:name, :description, :status, :quota, :comment, :service_provision_id)
    end
end

itsm/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :description, :category_id, :reference_api)
    end
end

itsm/app/helpers/application_helper.rb
module ApplicationHelper
end

itsm/app/helpers/categories_helper.rb
module CategoriesHelper
end

itsm/app/helpers/service_provisions_helper.rb
module ServiceProvisionsHelper
end

itsm/app/helpers/services_helper.rb
module ServicesHelper
end

itsm/app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <p>
    <strong>Subsidized amount:</strong>
    <%= category.subsidized_amount %>
  </p>

</div>

itsm/app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :subsidized_amount, style: "display: block" %>
    <%= form.number_field :subsidized_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

itsm/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

itsm/app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

itsm/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

itsm/app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

itsm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itsm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

itsm/app/views/service_provisions/_form.html.erb
<%= form_with(model: service_provision) do |form| %>
  <% if service_provision.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service_provision.errors.count, "error") %> prohibited this service_provision from being saved:</h2>

      <ul>
        <% service_provision.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :quota, style: "display: block" %>
    <%= form.text_field :quota %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :comment %>
  </div>

  <div>
    <%= form.label :service_provision_id, style: "display: block" %>
    <%= form.text_field :service_provision_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

itsm/app/views/service_provisions/_service_provision.html.erb
<div id="<%= dom_id service_provision %>">
  <p>
    <strong>Name:</strong>
    <%= service_provision.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= service_provision.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= service_provision.status %>
  </p>

  <p>
    <strong>Quota:</strong>
    <%= service_provision.quota %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= service_provision.comment %>
  </p>

  <p>
    <strong>Service provision:</strong>
    <%= service_provision.service_provision_id %>
  </p>

</div>

itsm/app/views/service_provisions/edit.html.erb
<h1>Editing service provision</h1>

<%= render "form", service_provision: @service_provision %>

<br>

<div>
  <%= link_to "Show this service provision", @service_provision %> |
  <%= link_to "Back to service provisions", service_provisions_path %>
</div>

itsm/app/views/service_provisions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Service provisions</h1>

<div id="service_provisions">
  <% @service_provisions.each do |service_provision| %>
    <%= render service_provision %>
    <p>
      <%= link_to "Show this service provision", service_provision %>
    </p>
  <% end %>
</div>

<%= link_to "New service provision", new_service_provision_path %>

itsm/app/views/service_provisions/new.html.erb
<h1>New service provision</h1>

<%= render "form", service_provision: @service_provision %>

<br>

<div>
  <%= link_to "Back to service provisions", service_provisions_path %>
</div>

itsm/app/views/service_provisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service_provision %>

<div>
  <%= link_to "Edit this service provision", edit_service_provision_path(@service_provision) %> |
  <%= link_to "Back to service provisions", service_provisions_path %>

  <%= button_to "Destroy this service provision", @service_provision, method: :delete %>
</div>

itsm/app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :reference_api, style: "display: block" %>
    <%= form.text_field :reference_api %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

itsm/app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p>
    <strong>Name:</strong>
    <%= service.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= service.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= service.category_id %>
  </p>

  <p>
    <strong>Reference api:</strong>
    <%= service.reference_api %>
  </p>

</div>

itsm/app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

itsm/app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <% @services.each do |service| %>
    <%= render service %>
    <p>
      <%= link_to "Show this service", service %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path %>

itsm/app/views/services/new.html.erb
<h1>New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

itsm/app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service) %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete %>
</div>